onlyBuiltDependencies:
  - sharp

overrides:
  ui: link:../../../Library/pnpm/global/5/node_modules/@nostr-git/ui
  '@nostr-git/ui': link:../../../Library/pnpm/global/5/node_modules/@nostr-git/ui
  '@nostr-git/shared-types': link:../../../Library/pnpm/global/5/node_modules/@nostr-git/shared-types
