onlyBuiltDependencies:
  - sharp

packages:
  - "packages/nostr-git/packages/core"
  - "packages/nostr-git/packages/ui"
  - "packages/nostr-git/packages/shared-types"
  - "packages/nostr-git/packages/git-wrapper"
  - "packages/nostr-git/packages/*"
